name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    
    - name: Build Docker image
      run: |
        docker build -t cholong_be:1.0.1 .
        docker tag cholong_be:1.0.1 ${{ secrets.DOCKERHUB_USERNAME }}/cholong_be:1.0.1
        
    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cholong_be:1.0.1

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest 

    steps:
      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: | 
            sudo docker version
